### ISSUE TITLE
Apparent error trying to learn identity function

### ISSUE THREAD

**Issue by travisbrady** [alkant/cpm#1]
When experimenting with CPM via the Python interface I've gotten some confusing results.
I tried with xor (with labels 0 and 1) and was getting values back in the `assignments` array not in the label set (eg 3, 4, 17, etc.) and these values changed when I added subclassifiers or sgd iterations.

Here is the simplest example, am I doing something wrong here? How could `assignments` always be 0 when the input labels were always 1?

``` python
In [31]: ds = cpm.Dataset(np.ones(10, dtype=np.float32).reshape(10, 1), np.ones(10, dtype=np.int32))
In [32]: clf = cpm.CPM(10)
In [33]: clf.fit(ds)
In [34]: clf.predict(ds)
Out[34]:
[array([ 1.4661082,  1.4661082,  1.4661082,  1.4661082,  1.4661082,
         1.4661082,  1.4661082,  1.4661082,  1.4661082,  1.4661082], dtype=float32),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)]
```

Platform:

```
$ uname -a 
14.1.0 Darwin Kernel Version 14.1.0: Thu Feb 26 19:26:47 PST 2015; root:xnu-2782.10.73~1/RELEASE_X86_64 x86_64
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix
```

**Comment by alkant** [comment]
@travisbrady thank you for the question. The output of `predict()` is a bit confusing but everything looks OK in your example.

First, CPM only does binary classification. If you have multi-class data, you can select which class you want the CPM to detect by using the `outer_label` option of the constructor (defaults to 1). In your case, everything is binary indeed and it would be rightfully strange to have multi-class outputs.

If you are only interested in the prediction the model makes, you have to look at the first vector returned by `predict()`, the `scores`. These are the margins (+sign) of the model for the instances. When `score > 0`, the inferred class is `outer_label`. In your case, everything is fine, the model predicts all of the 10 instances as belonging to class 1.

The second, `assignment` array only makes sense for the CPM model. Internally, CPM works by maintaining `k` sub-classifiers. The `assignments` array tells you which sub-classifier was used for the prediction. This is useful when you want to understand the structure of the `outer_label` class, as each positive margin example gets associated with a single sub-classifier. You can think of it as an implicit clustering for that class. In your case, all of the examples belong to the same cluster `0`, which also makes sense.

**Comment by alkant** [comment]
I'm closing this now, but you can always reopen it.

**Comment by travisbrady** [comment]
Thanks, Alex. This was very helpful.
I've begun some rough experimental OCaml bindings to CPM here: https://github.com/travisbrady/ocaml-cpm

I'm going to clean them up and then attempt some experiments.
